[MH3G_CharmTableReroll_JP_HD]
moduleMatches = 0x2ad22bd7

# How it works
# - Charms are generated by the function at 0x02156990 (charms picked up in a quest are generated together
#   when they are identified after the quest). Every value comes from channel 1 of the game's random number
#   generator (object at *0x10298CE0, state at +0x42), which steps as x <- 176 * x mod 65363.
# - 65363 = 163 * 401, so the value never leaves the cycle it starts on. The cycle is the charm table.
#   Values that are multiples of 163 or 401 sit on the short cycles (the cursed tables).
# - At the start of charm generation this patch replaces the channel with a new value: 1..65362 and not a
#   multiple of 163 or 401. It does so for every charm ($everyCharm = 1) or only for the first charm after
#   boot ($everyCharm = 0). The new value mixes the time base with the current channel value.
# - The code cave keeps the number of re-rolls, the last value and the last 8 values for checking.

.origin = codecave

_mh3gCharmReroll_Count:
.int 0
_mh3gCharmReroll_Seed:
.int 0
_mh3gCharmReroll_Log:
.int 0, 0, 0, 0, 0, 0, 0, 0

_mh3gCharmReroll_Hook:
lis r12, ha(_mh3gCharmReroll_Count)
lwz r0, lo(_mh3gCharmReroll_Count)(r12)
cmpwi cr0, r0, 0
beq _mh3gCharmReroll_Pick
li r11, $everyCharm
cmpwi cr0, r11, 0
beq _mh3gCharmReroll_Exit
_mh3gCharmReroll_Pick:
.int 0x7D6C42E6
lis r12, 0x102A
lwz r12, -0x7320(r12)
lhz r12, 0x42(r12)
slwi r12, r12, 16
xor r11, r11, r12
lis r12, 0x9E37
ori r12, r12, 0x79B1
mullw r11, r11, r12
srwi r11, r11, 8
li r12, 0
ori r12, r12, 0xFF52
divwu r0, r11, r12
mullw r0, r0, r12
subf r11, r0, r11
addi r11, r11, 1
_mh3gCharmReroll_Check:
li r12, 163
divwu r0, r11, r12
mullw r0, r0, r12
cmpw cr0, r0, r11
beq _mh3gCharmReroll_Bump
li r12, 401
divwu r0, r11, r12
mullw r0, r0, r12
cmpw cr0, r0, r11
bne _mh3gCharmReroll_Store
_mh3gCharmReroll_Bump:
addi r11, r11, 1
b _mh3gCharmReroll_Check
_mh3gCharmReroll_Store:
lis r12, 0x102A
lwz r12, -0x7320(r12)
sth r11, 0x42(r12)
lis r12, ha(_mh3gCharmReroll_Seed)
stw r11, lo(_mh3gCharmReroll_Seed)(r12)
lis r12, ha(_mh3gCharmReroll_Count)
lwz r0, lo(_mh3gCharmReroll_Count)(r12)
rlwinm r12, r0, 2, 27, 29
addis r12, r12, ha(_mh3gCharmReroll_Log)
stw r11, lo(_mh3gCharmReroll_Log)(r12)
addi r0, r0, 1
lis r12, ha(_mh3gCharmReroll_Count)
stw r0, lo(_mh3gCharmReroll_Count)(r12)
_mh3gCharmReroll_Exit:
mr r29, r4
blr

# The hook replaces "mr r29, r4" right after the prologue (LR is already saved on the stack there).
# Only r0, r11, r12 and cr0 are touched; none of them is live at this point.
0x021569B8 = bl _mh3gCharmReroll_Hook
